### PR TITLE
Fix Budapest feed!

### PR DESCRIPTION
**Pull request by Altonss**
Fix Budapest feed!

### CODE REVIEW

**Comment by Altonss** [comment]
I don't see Budapest updated on citybik.es . Is the new feed failing?

**Comment by Altonss** [comment]
It is still not updated on https://citybik.es, is this normal @eskerda ?

**Comment by eskerda** [comment]
Fixed by https://github.com/eskerda/pybikes/commit/474a512be6e8c6928056d83e6ddb03204067f8c7

Changing the domain was not enough, the id needed to correlate

**Comment by Altonss** [comment]
Sorry for my mistake, and thanks a lot for your work!

**Pull request merged**
