### PR TITLE
nextbike.pl cities

### PR DESCRIPTION
**Pull request by thesebas**

### CODE REVIEW

**Comment by eskerda** [comment]
Hey, sorry for not looking into this. I'd github notifications disabled and been out for a while. Will look at it ASAP

**Comment by eskerda** [comment]
LGTM, except the naming of bike share systems.

Is Poland strictly necessary on the name (as in, it's Poland present on the official name?)

**Comment by eskerda** [comment]
As for maintaining a fork of the API. Be my guest: https://github.com/eskerda/citybikes-api

**Comment by thesebas** [comment]
Yeah, it seems I've been mindlessly copy-pasting network names from nextbike API xml, fixed that. Also added one new city that appeared in API.

**Comment by eskerda** [comment]
Cool, thanks for contributing!

I've ran nextbike.json through an slugify script resulting in the following: https://github.com/eskerda/PyBikes/commit/298d741242b32e872535debd8fe33bdcd0a10102

**Comment by eskerda** [comment]
@thesebas Ok, server upgraded.

You should be able to see all added networks on the following map http://upcoming.citybik.es/ and OC on any app using the citybikes API.

**Comment by thesebas** [comment]
OMG, I'm so excited, big THX! Poland looks pretty covered now but strangely there is missing one city marker (https://nextbike.net/maps/nextbike-live.xml?domains=pl).

**Comment by eskerda** [comment]
Hmm, seems the lat/lng for Wrocławski Rower Miejski was incorrectly set.

**Comment by thesebas** [comment]
Yup, silly me, thx ;)

**Pull request merged**
