### PR TITLE
Add Föli bikes in Turku, Finland

### PR DESCRIPTION
**Pull request by ZeiP**
The patch adds support for the Föli-fillari-system by Turku regional traffic in Turku, Finland. It uses the Digitransit API.

### CODE REVIEW

**Comment by eskerda** [comment]
Looks good, many thanks @ZeiP!

**Comment by eskerda** [comment]
@ZeiP I assume the system is not run by nextbike anymore? In any case, I prefer this feed than using the one by nextbike.

**Comment by eskerda** [comment]
Deleted nextbike entry at https://github.com/eskerda/pybikes/commit/01a1aff44690a1963f987b31a62f3ee91c3faba9

**Comment by ZeiP** [comment]
It actually is run by Nextbike, I have to admit I missed the fact that Nextbike API was already listed in the service. I do still think it's better to use the Digitransit API, because that's the one providing the official route guide and application data; I suppose the data should be the same but this way the integration works even if/when the provider is changed.

**Pull request merged**
