### PR TITLE
add le velo star Rennes, FR

### LINKED ISSUE #235: Add Rennes (France) - Le Vélo STAR
Hi,

Firstly, thanks for the project! If you have the time, you can add the data of Rennes, France:

- Real time data: https://data.explore.star.fr/explore/dataset/vls-stations-etat-tr/api/
- Real time web-service: https://data.explore.star.fr/api/records/1.0/search/?dataset=vls-stations-etat-tr&facet=nom&facet=etat&facet=nombreemplacementsactuels&facet=nombreemplacementsdisponibles&facet=nombrevelosdisponibles

In the API, a *record* object is a station, and the fields are:

- `etat: "En fonctionnement"`: The station is opened
- `nombrevelosdisponibles`: Bikes available
- `nombreemplacementsactuels`: Total parking places
- `nombreemplacementsdisponibles`: Available parking places
- `coordonnees`: Latitude & longitude
- `nom`: Name of the station
- `idstation`: Unique identifier of the station
- `lastupdate`: Latest update of the data

If you have any questions, feel free to ask me!

### PR DESCRIPTION
**Pull request by BenSto**
feel free to have a look. potentially closes #235

### CODE REVIEW

**Comment by BenSto** [comment]
Shall I close the PR?

**Comment by BenSto** [comment]
I'm closing this due to inactivity, feel free to reopen anytime if you like @eskerda

**Comment by eskerda** [comment]
Closed in favor of https://github.com/eskerda/pybikes/pull/305

**Comment by BenSto** [comment]
> Closed in favor of #305

Ok, sorry I didn't recognize that there are more stations/data available and the scraper didn't cover these. Thanks for fixing etc. 🚲

**Pull request closed without merging**
