### PR TITLE
feat(levelo-ampmetropole): Add new API for LeVelo bike sharing system

### PR DESCRIPTION
**Pull request by Ephtolens**
Hi @eskerda 

A New Bike sharing system has been deployed in Marseille, France, by Fifteen

You'll find here is the json for stations details : https://levelo.ampmetropole.fr/api/stations

I've implented .json for fifteen and .py for fifteen too

There is no field in the response json to know how many free spaces are left on each station, for now I've randomly put 15 - availableBike instead, waiting for the city of Marseille to answer me on this point.

Everything seems to work well otherwise

Thanks

### CODE REVIEW

**Comment by Manu1400** [comment]
bicycles / stations : 2000/200 = 10
[https://www.youtube.com/watch?v=FCMKAZ3Kw3A](source)

**Comment by eskerda** [comment]
If no such information is available, we could probably set it to `None`, although I see the play on words of using 15!

**Comment by Ephtolens** [comment]
Thanks, After downloading the mobile app I've seen some stations with more than 10 bikes (i.e. 22) That invalide the theory of 10 or 15 (😢) I'll wait for the response of the provider, otherwise i'll set it to None, maybe there is no limit, I'll keep you in touch.

**Comment by Ephtolens** [comment]
I've added VLS for Epinal too because it's also provided by fifteen and json data are pretty similar (but not strictly identical)
After some reading, it's seems that each station have a capacity of 10 bikes. But you can still drop your bike near the station if it's full or even in a temporary virtual station close to the real one.
I've set free to 10 - bikes then and set it to 0 if there is 10 or more bikes already in stations.

A possible improvement could be to add a field in the BikeShareStation object to say wether or not it's possible to drop your bike even if there is no room for it like a 'overflowing' or 'overflow_authorized' boolean at False by default or an int to say how many bike you can drop near the station. More and more provider let this happen now.

**Comment by Ephtolens** [comment]
Answer of fifteen at the moment : 

> Stations are composed of 1 to 4 edocks, each edocks have a capacity of 10 bikes
> Mot of the stations are composed of 2 edocks 

This data is not yet in the json data, I'll ask them when they think it's gonna happen. I let this pull request pending till then

Have a good day

**Comment by Manu1400** [comment]
## an other city: Saint-Brieuc (France), by FIFTEEN
https://www.data.gouv.fr/fr/datasets/location-de-velos-velobaie/
> Ces données au format “GBFS” (General Bikeshare Feed Specification) nous sont transmises par **FIFTEEN**, fournisseur du service.

GET https://gateway.prod.partners-fs37hd8.zoov.site/gbfs/2.2/saintbrieuc/en/gbfs.json?key=YmE1ZDVlNDYtMGIwNy00MGEyLWIxZWYtNGEwOGQ4NTYxNTYz
```js
{"last_updated":1671627662,"ttl":30,"version":"2.2","data":{"en":{"feeds":[{"name":"gbfs","url":"https://gateway.prod.partners-fs37hd8.zoov.eu/gbfs/2.2/saintbrieuc/en/gbfs.json"},{"name":"system_information","url":"https://gateway.prod.partners-fs37hd8.zoov.eu/gbfs/2.2/saintbrieuc/en/system_information.json"},{"name":"station_status","url":"https://gateway.prod.partners-fs37hd8.zoov.eu/gbfs/2.2/saintbrieuc/en/station_status.json"},{"name":"station_information","url":"https://gateway.prod.partners-fs37hd8.zoov.eu/gbfs/2.2/saintbrieuc/en/station_information.json"},{"name":"vehicle_types","url":"https://gateway.prod.partners-fs37hd8.zoov.eu/gbfs/2.2/saintbrieuc/en/vehicle_types.json"},{"name":"free_bike_status","url":"https://gateway.prod.partners-fs37hd8.zoov.eu/gbfs/2.2/saintbrieuc/en/free_bike_status.json"},{"name":"system_pricing_plans","url":"https://gateway.prod.partners-fs37hd8.zoov.eu/gbfs/2.2/saintbrieuc/en/system_pricing_plans.json"},{"name":"geofencing_zones","url":"https://gateway.prod.partners-fs37hd8.zoov.eu/gbfs/2.2/saintbrieuc/en/geofencing_zones.json"}]}}}
```
=> have an issue in GBFS data: missing `key` param in URLs

**Comment by tuxayo** [comment]
> This data is not yet in the json data, I'll ask them when they think it's gonna happen. I let this pull request pending till then

Thanks a lot for the patch, research and reach out to the provider. If they don't answer quickly or give a long or uncertain delay, is there anything else to do for this patch?

Meanwhile: here is the map for anyone needing the info: https://levelo.ampmetropole.fr/sharing#stationsMap

**Comment by Ephtolens** [comment]
I'm in direct contact with fifteen now, I'll dig in with them and suggest them improvement for their API.
I'm vacationing for a few days, I'll keep you (and the code) update in my free time !

Enjoy the end of the year :santa: !

**Comment by eskerda** [comment]
@Ephtolens What are the implementation differences between `VeloBaie` and `Vilvolt`? I have tried to look at the differences but besides checking for `statusCode` on the response I do not see anything else that is obvious.

Thanks for your help!

**Comment by Ephtolens** [comment]
Hi, I think you mean between Levelo (Marseille) and Vilvolt ?
That's because the 2 returned json are not the same, one have the status field, and not the other one...
Actually Fifteen told me that they could expose a GBFS, which is going to be much simpler. A soon as I have the URL I'll update my code (or close this PR and open a new clean one, as you want !)

They take a bit of time to respond cause of the end of the year, nobody's working :laughing: 

I'll keep you in touch !

**Comment by tuxayo** [comment]
The official website map is a pain to use [1] and it's very needed with the operator transition, growing network and new stations in new places.

If the current proposed code is good enough without major work needed, can it be merged to have something while GBFS comes up? The code is nicely isolated to the new fifteen.py file so it won't be more work to have it merged (if no big QA issue) compared to have it pending to be dropped when the new endpoint will come up.

[1] and it has trackers and a bloody YouTube video that loads even if thankfully it doesn't play.

**Comment by eskerda** [comment]
Integrated changes into https://github.com/eskerda/pybikes/pull/536

**Comment by tuxayo** [comment]
Thanks a lot! I can finally use BikesSharingHub again ^o^

It's not a big deal that it shows all stations either empty (0 bikes) or fully (any number). The website doesn't show the slots anyway. That will do until Fifteen provides a new endpoint with more data.

**Pull request closed without merging**
