### PR TITLE
Add Velobike station based bikesharing Astana

### PR DESCRIPTION
**Pull request by BenSto**
I have seen this Provider in Astana, Kazachstan. Their Webservice is unfortunately very slow, so I dont know if this is a candidate for the System. Maybe you can have a look by yourself @eskerda . Thanks in advance!

### CODE REVIEW

**Comment by eskerda** [comment]
Checking...

**Comment by BenSto** [comment]
> Checking...

seems like there is something like a winter break in astana, maybe next spring they start the service again... :disappointed:

**Comment by eskerda** [comment]
Weird, last time I checked the URL endpoint was not working.

System added, sorry for the delay. Hope next spring it can be useful to you

**Comment by BenSto** [comment]
Yeah I think their webservice is not very stable, maybe that was the problem. Thanks for merging! :bike:

**Pull request merged**
