### PR TITLE
add more nextbike instances

### PR DESCRIPTION
**Pull request by eUgEntOptIc44**
Hi @eskerda :wave:

I discovered this great project just recently. I worked with data from nextbikes German locations in the past for another project. For some reason I didn't found your repo back than.

I thought it might be useful to extend the list of nextbike instances. I parse the data from the API endpoint [`https://api.nextbike.net/maps/nextbike-live.json`](https://api.nextbike.net/maps/nextbike-live.json) using the code published in this [gist](https://gist.github.com/eUgEntOptIc44/66a3c18924312be29ef27d9d1a19c842). I basically run a bit of validation and search-and-replace on the data to remove outdated data and entries meant to be used for internal tests.

Hope you might have the time to look into this PR. Looking forward to your feedback on this.

Regards,

Jean-Luc

### CODE REVIEW

**Comment by Altonss** [comment]
Woow thanks a lot for this amaizing work!
(I manually made this small PR https://github.com/eskerda/pybikes/pull/492 to resolve https://github.com/eskerda/pybikes/issues/491, but it can be closed if this gets merged before!)
It might be intereting to run your "gist" regularly to check for new networks or deprecated ones, would some github action work for this purpose?

**Comment by eUgEntOptIc44** [comment]
Hi @Altonss :wave:

first of all thank you for the kind words. I faced a rather dated documentation of the API when trying to analyze the data for my project last year. So I thought that I might be worth the effort to ease the bar for future users. You see by the size of the initial json response (ca. 50mb as of writing) that the database powering this dataset is quite massive. Nextbike operates world wide so I guess there's still hidden potential.

Also see https://sharedmobility.github.io/Nextbike.html for GBFS feeds if your interested in that sort of things.
(It's basically the way how google maps integrates data of shared mobility (bikes, scooters, cars) in it's service)

Running the source code from the gist on a regular basis might be a good idea. However there's still too much human interaction need to fully automate it. (say e.g. in a git based workflow)

**Comment by Altonss** [comment]
> Also see https://sharedmobility.github.io/Nextbike.html for GBFS feeds if your interested in that sort of things. (It's basically the way how google maps integrates data of shared mobility providers (bikes, scooters, cars) in it's service)

We also have support for GBFS so we could move to these feeds. Is any of this 2 feeds (gbfs or nextbike API) better in terms of refresh rate/ amount of information?

> Running the source code from the gist on a regular basis might be a good idea. However there's still too much human interaction needed to fully automate it. (say e.g. in a git based workflow)

Yes so manual update once in a while (and if users open issues about requested networks or broken ones) might sound sufficient ;)

**Comment by eskerda** [comment]
Hey @eUgEntOptIc44! Thanks for the efforts on bringing up to date our nextbike feeds. I know from experience this is no easy task, and as you say, even if a big chunk of the work can be automated, there's still a lot of needed manual reviewing work: location centers not always being precise enough, inconsistent naming, ...

I have always kept a bit of a laissez-faire attitude towards nextbike feeds on pybikes, but it has always bothered me how much churn there is associated with it. Nextbike is a very active development, so there are cities appearing and disappearing and lots of small sized pilots with little activity. Any new feed is a feed we need to support, or remove at some point when it disappears. For me, I am happy to merge in _any_ feed that is useful to whoever is adding it, but having lots of feeds just because we can is a strategy I know brings a lot of future work. For that reason, and with nextbike in particular, I want to re-evaluate which feeds we want to support. Probably just a filter based on size is enough and a good start.

That being said, I am happy to merge in your changes, but just knowing that I might remove some of the feeds in the near future.

**Comment by Altonss** [comment]
> For that reason, and with nextbike in particular, I want to re-evaluate which feeds we want to support. Probably just a filter based on size is enough and a good start.

I fully understand that point of view, but also think each added network can be usefull for a user, even the smallest one :)

**Comment by eskerda** [comment]
Reported errors are minor, mostly related on how citybikes expects tags to work:

Non unique tags

```
FAILED tests/test_instances.py::TestNextbike::test_tag_unique[nextbike.Nextbike::mvrad0]
FAILED tests/test_instances.py::TestNextbike::test_tag_unique[nextbike.Nextbike::mvrad1]
FAILED tests/test_instances.py::TestNextbike::test_tag_unique[nextbike.Nextbike::vvtregiorad0]
FAILED tests/test_instances.py::TestNextbike::test_tag_unique[nextbike.Nextbike::vvtregiorad1]
```

Unallowed characters on the tag name (underscore)
```
FAILED tests/test_instances.py::TestNextbike::test_fields[nextbike.Nextbike::vag_rad]
FAILED tests/test_instances.py::TestNextbike::test_fields[nextbike.Nextbike::bergisches_e-bike]
```

**Comment by eUgEntOptIc44** [comment]
Hi @eskerda

thank you for the fast reaction to my PR. As noted above I applied your feedback to fix the typos in the tags. I agree with your statement on the issue of adding a big numbers of feeds with possible (future) outages and resulting in issue here on the repository.

To my personally it would be important to add 'VAG_rad' (Nürnberg[^1]) and 'OLIbike' (Oldenburg). Removing other nonfunctional feeds would be totally fine for me. But as @Altonss mentioned [above](https://github.com/eskerda/pybikes/pull/495#issuecomment-1203287300) I think the more feeds the better. However keeping the support demand on a reasonable level has a higher priority from my point of view.

[^1]: *Nuremberg* in English

**Pull request merged**
