### PR TITLE
[nextbike] Polish networks updates

### PR DESCRIPTION
**Pull request by adamdanielczyk**
Since my another PR with thorough nextbike stations update (https://github.com/eskerda/pybikes/pull/247) is apparently going nowhere, I am publishing Polish networks update.

Since the beginning of 2017 bike season, lots of new networks have opened up in Poland. As such, the nextbike.json file needed updating.

Please let me know @eskerda should you have any suggestions.

### CODE REVIEW

**Comment by eskerda** [comment]
Sorry about the other PR. Since list of changes was pretty big it either takes a lot of time to check, which is scarce, or a leap of faith, which I am doing with this one.

Feel free to update the other one, since nextbike support is pretty messed up ATM, I guess its better to have working systems even if some go away than bad support for the network

**Comment by adamdanielczyk** [comment]
Alright, understood. It's just that I have not received any response and was worried about it ever getting merged - I have some users of my Android application who were getting frustrated that their city is not visible in the app.

I will try to come up with some script that could hopefully be merged into this repository and run every so often so that the json file stays up-to-date. For now, I have used this script https://github.com/adamdanielczyk/pybikes/blob/nextbike-parser/utils/nextbike-parser.py but it could use some improvements.

**Comment by adamdanielczyk** [comment]
@eskerda By the way, I have noticed in the api that some networks seem to be doubled or even tripled - the json does not seem to contain duplicates. What could be wrong?

**Comment by eskerda** [comment]
Fixed, thanks for reporting!

**Comment by adamdanielczyk** [comment]
Good job, thank you :)

On Jul 31, 2017 23:42, "eskerda" <notifications@github.com> wrote:

Fixed, thanks for reporting!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/eskerda/pybikes/pull/273#issuecomment-319205136>, or mute
the thread

**Pull request merged**
