### PR TITLE
python2 python3 compatible idioms

### PR DESCRIPTION
**Pull request by MartinoMensio**
The scope of this PR is to provide a python module independent from the 2vs3 problem.
I wanted to use pybikes in python3 without breaking the python2 version. So I used the suggestions on http://python-future.org/compatible_idioms.html and applied them by hand.
This should be tested well because the changes are a lot. I only run few tests by hand on the most critical parts.
Let me know your opinion!

### CODE REVIEW

**Comment by MartinoMensio** [comment]
I still get a lot of errors running the full tests. Will tell you when seems ready

**Comment by eskerda** [comment]
:+1:  good job so far! Let me know if I can help

**Comment by MartinoMensio** [comment]
A list of failing tests on the master could be useful, because I am trying to understand the cause of all the errors and failures.

In this comment I will keep track of what is failing on the full testing. Consider that I am testing on the merge of this PR and this other https://github.com/eskerda/pybikes/pull/283.

## Sources of errors

- NET -> connection error or related to changes in the scraped pages
- ENC -> porting error (I am working on those)
- ??? -> needs more investigation

```
NET 0 bicipalma.py", ConnectionError http://83.36.51.60:8080
ENC 1 bixi.py", line 50, in get_xml_stations ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
KEY 2 bysykkel.py", line 38 KeyError: u'stations'
??? 3 callabike.py", line 34 ValueError: No JSON object could be decoded
??? 4 bixi.py", line 67, in get_json_xml_stations ValueError: No JSON object could be decoded
??? 5 samba.py", line 133, in update AttributeError: 'NoneType' object has no attribute 'group'
NET 6 punpunbikeshare.py" ConnectionError: HTTPConnectionPool(host='pcc.punpunbikeshare.com', port=80): Max retries exceeded with url: /index.php?r=api2/listStations&token=1111&key=3e5cc0883cf7134b6b3ea7157d2cb4ef (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6985461ed0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
ENC 7 bixi.py", line 50 ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
??? 8 velobike.py", line 29 ValueError: No JSON object could be decoded
NET 9 veloway.py", line 33 ConnectionError: HTTPConnectionPool(host='www.velocea.fr', port=80): Max retries exceeded with url: /cartoV2/libProxyCarto.asp (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f69854a5a50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
??? 10 bixi.py", line 55 ValueError: Expecting object: line 1 column 41 (char 40)

ENC 11 bonopark.py", line 47 TypeError: b'APP_INICIO' is not JSON serializable
??? 12 gobike.py", line 60, in _get_all_pages TypeError: 'float' object cannot be interpreted as an integer
ENC 13 keolis.py", line 81, in __init__ LookupError: unknown encoding: string-escape
```

## Errors
python2 failures                    error
```
test_bicipalma                      0
test_bixi                           1
test_bixi-montreal                  1
test_callabike                      3
test_callabike-berlin               3
test_callabike-darmstadt            3
test_callabike-frankfurt            3
test_callabike-frankfurt-airport    3
test_callabike-koln                 3
test_callabike-luneburg             3
test_callabike-marburg              3
test_callabike-munchen              3
test_callabike-russelsheim          3
test_callabike-stuttgart            3
test_callabike-wiesbaden            3
test_konrad                         3
test_melbourne-bike-share           4
test_mibicitubici                   5
test_punpunbikeshare                6
test_santander-cycles               7
test_stadtrad                       3
test_velobike                       8
test_velocea                        9
test_veloway                        9
test_we-cycle                       10
```
python3 failures
```
test_bicimad                        11
test_bicipalma                      0
test_bixi                           1
test_bixi-montreal                  1
test_bonopark                       11
test_bycyklen                       12
test_bysykkelen                     12
test_callabike                      3
test_callabike-berlin               3
test_callabike-darmstadt            3
test_callabike-frankfurt            3
test_callabike-frankfurt-airport    3
test_callabike-koln                 3
test_callabike-luneburg             3
test_callabike-marburg              3
test_callabike-munchen              3
test_callabike-russelsheim          3
test_callabike-stuttgart            3
test_callabike-wiesbaden            3
test_gobike                         12
test_idecycle                       13
test_keolis                         13
test_konrad                         3
test_melbourne-bike-share           4
test_mibicitubici                   5
test_nu-connect                     12
test_punpunbikeshare                6
test_santander-cycles               7
test_stadtrad                       3
test_velobike                       8
test_velocea                        9
test_veloway                        9
test_we-cycle                       10
```

## Assertion failures
All the systems below (except those marked with a `*`) fail because of `FAILs self.assertTrue(len(instance.stations) > 0)`.
The `*` means that the failing assertion is
```text
*
nextbike.py", line 55, in update
    self.uid, self.domain, self.url
AssertionError: Not found: uid XXX, domain 'la', url https://nextbike.net/maps/nextbike-live.xml?domains=la&get_biketypes=1
```

List

```
test_bcycle
test_bicikelj
test_bicloo
test_bikebrasilia
test_bikepoa
test_bikerecife
test_bikerio
test_bikesalvador
test_bikesampa
test_bysykkel-lillestrom
test_citycycle
test_cristolib
test_curtin-bike-share
test_cyclic
test_cyclocity
test_dublinbikes
test_ecobici-buenos-aires
test_ecobici_ba
test_emovity
test_gbfs
test_girocleta
test_goeteborg
test_le-velo
test_li-bia-velo
test_lundahoj
test_nextbike           *
test_nextbike-haag      *
test_nextbike-hyderabad *
test_nextbike-panama    *
test_nextbike-rotterdam *
test_nextbike-salzburg  *
test_relay-atlanta
test_samba
test_santiago
test_sevici
test_smoove
test_toyama-cyclocity
test_tusbic
test_valenbisi
test_velam
test_velib
test_velik
test_velivert
test_velo
test_velo2
test_velocite-besancon
test_velocite-mulhouse
test_veloh
test_velostanlib
test_velov
test_villo
test_vilnius-cyclocity
test_zgierski-rower-miejski-zgierz
```

**Comment by MartinoMensio** [comment]
Hello @cyrinux I cannot currently finish the porting work. The tests pass but I remember there were some issues specific to some bike systems. You have to check city by city because somewhere there are problems.

**Comment by cyrinux** [comment]
Hell guys,

thanks for your replies and work.
I will follow this PR and adopt this lib when this will be merged for my
py3status module.

**Comment by cyrinux** [comment]
Thanks @eskerda ! I will give an eye to this too :) You have well understand the project :)

**Pull request closed without merging**
