### PR TITLE
cleanup __init__ and update tests

### PR DESCRIPTION
**Pull request by eskerda**
* move tests to pytest
* remove churn from `__init__`

### Missing
* either deprecate python 2 completely or make sure these changes work fine

### Motivation
This PR is part of a series of PRs to:
* bring back CI
* publish proper packages

### CODE REVIEW

**Comment by Altonss** [comment]
Woow thanks for these changes! So Pybikes is now fully compatible with Python 3?

**Comment by eskerda** [comment]
> Woow thanks for these changes! So Pybikes is now fully compatible with Python 3?

Has been working for a while with python 3!

**Comment by Altonss** [comment]
> Has been working for a while with python 3!

Woow really cool! With the old readme I thought that Python 2 was still needed xD

**Comment by eskerda** [comment]
> > Has been working for a while with python 3!
> 
> Woow really cool! With the old readme I thought that Python 2 was still needed xD

Since idk how long this PR will be open, I just updated the README removing that part, Thanks!

**Pull request merged**
