### PR TITLE
update orlando juice url

### PR DESCRIPTION
**Pull request by anastmag**
Update url of orlando juice bike share.

### CODE REVIEW

**Comment by eskerda** [comment]
About Abu Dhabi, we already have them supported in https://github.com/eskerda/pybikes/blob/master/pybikes/adcb.py

**Comment by anastmag** [comment]
Oh haven't noticed that

**Comment by eskerda** [comment]
@anastmag Maybe we can remove the part of this PR that touches ADCB and just make it a small one changing the URL for orlando juice bike share? We can merge that PR in an instant :)

**Comment by altagir** [comment]
Abu Dhabi has also gbfs support :
https://api-core.bikeshare.ae/gbfs/gbfs.json

**Comment by altagir** [comment]
@eskerda Maybe you should prefer the GBFS version of Abu Dhabi to the BSS format.... In that case, this pull request should delete the old spec for Abu Dhabi.

GBFS have extra fields eightd_has_key_dispenser in station_information.json to cover the old BSS fields for bike key dispenser flags... (extra.has_bike_keys)

**Comment by anastmag** [comment]
Ready

**Comment by eskerda** [comment]
Thanks @anastmag and @altagir!

Feel free to open a new PR with the Abu Dhabi changes, where we can discuss if its better or not than our current feed and add support for any additional fields that might be necessary (?).

**Pull request merged**
