### PR TITLE
added rtcbikeshare and spokies

### PR DESCRIPTION
**Pull request by anastmag**
Addresses #200

### CODE REVIEW

**Comment by Altonss** [comment]
This pull request seems fine to me! Could it get merged?

**Comment by Altonss** [comment]
This could maybe me merged also @eskerda ?

**Comment by Altonss** [comment]
Some conflicts must be resolved first, but as I don't have write access, I can't do anything here to help...

**Comment by eskerda** [comment]
> Some conflicts must be resolved first, but as I don't have write access, I can't do anything here to help...

you do not need write access to fix conflicts between public branches and repos

**Comment by Altonss** [comment]
> you do not need write access to fix conflicts between public branches and repos

How could I do?

**Comment by Altonss** [comment]
I have integrated the proposed changes in a new PR, so this one can be closed in favor of #479 ;)
No more conflicts on my PR :)

**Comment by eskerda** [comment]
include in https://github.com/eskerda/pybikes/commit/e41966f3773178b1b526e87b9689222c3c29ede2

thanks @anastmag @Altonss

**Pull request closed without merging**
