### PR TITLE
Add Veloway system

### PR DESCRIPTION
**Pull request by bparmentier**
I'm not sure how to handle the encoding of the `wcom` tag. Could you give it a try?

### CODE REVIEW

**Comment by eskerda** [comment]
Seriously, indeed, WTF at ```wcom```, wouldn't touch that with a long poking stick.No wonder it takes a human life to render a map on their website. Thinking about adding a Hall of Shame of different gems we find on our journey. 

Note that some feeds do not include ```wcom``` (well, as null), failing at fix_name and not appending it to the stations list. For instance, vel'in just reports back 1 station
```
$ virtualenv2 v
$ source v/bin/activate
(v) $ sh runtests.sh TestSystems.test_veloway
[...]
Vélo Bleu has 166 stations
↑ stations look ok ↑                          

DK'Vélo has 31 stations
↑ stations look ok ↑                          

Vélocéa has 24 stations
↑ stations look ok ↑                          

Vél'in has 1 stations
↑ stations look ok ↑  
.
----------------------------------------------------------------------
Ran 1 test in 4.778s

OK
```
* My recommendation would be to just drop  ```wcom```, as what it does provide is rather funky, varying from a human-readable address to just ```17 Station```. There's an open issue (#21) about adding a cohesive address field to all stations. 
* Should we drop stations that have neutral set to 1 (assuming that could happen)?
* I can't grasp the difference between ```ac``` and ```tc```.

**Comment by bparmentier** [comment]
* Hey, got it working (I think) in https://github.com/bparmentier/PyBikes/commit/65b101ca354167d5e44fff48b5893cde3f9791d6. We could have dropped the `wcom` tag but the problem remains in `name` anyway…
* We could keep `neutral`, but I don't see any real difference with `disp`. Should be discussed.
* As I understand it, `tc` is the number of slots physically present, while `ac` is the number of working slots (some may be deactivated/broken/malfunctionning).

**Comment by eskerda** [comment]
Good, thanks. Note that ``` if foo is not None and foo != ""``` is equivalent to ```if foo```

**Comment by bparmentier** [comment]
> Note that if foo is not None and foo != "" is equivalent in python to if foo

Fixed.

Maybe should I also drop `extra['slots_available']` and just use `ac` for `extra'[slots']`. What do you think?

**Comment by eskerda** [comment]
If the info is there, I would use it. On another feed we've got ```faulty_slots```, but I think ```slots_available``` makes sense in this case.

**Comment by eskerda** [comment]
And off we go! 4 new bike sharing schemes. Many thanks!

**Pull request merged**
