### PR TITLE
get_biketypes is now provided by default, default API host: api.nextb…

### PR DESCRIPTION
**Pull request by j0kan**
…ike.net

### CODE REVIEW

**Comment by robbi5** [comment]
Great 👍 
But it's currently not the default on `mvgrad.nextbike.net`, so requests for munich still require `get_biketypes=1`

**Comment by j0kan** [comment]
You're right so rather wait another 2-3 weeks until mvgrad has the latest software, too.

**Comment by Altonss** [comment]
Is this PR still relevant 6 years later, or could it be closed?

**Comment by j0kan** [comment]
Still relevant - should be merged.

**Pull request closed without merging**
