### PR TITLE
[Samba] Update URLs, add Belem and Goiania

### PR DESCRIPTION
**Pull request by edumucelli**
Among fixes, this one addresses #279.

### CODE REVIEW

**Comment by eskerda** [comment]
@edumucelli Sorry, forgot about this. Looks perfect, thanks!

`bikerecife` and `mibicitubici` servers doesn't seem to respond. Maybe they are migrating too?

**Comment by edumucelli** [comment]
@eskerda `bikerefice` seems to have been moved to https://bikeitau.com.br/mapa-das-estacoes/. Seems like `mibicitubici` is temporarily gone, even the app is not working, guess the API has gone as well.

**Comment by igormatos** [comment]
@edumucelli are you going to update `bikerecife`? I can try to help with that.

**Comment by eskerda** [comment]
@igormatos my bad, looking at the new recife site, it looks like a completely new implementation.

**Comment by igormatos** [comment]
@eskerda no problem!  Yeah, it is a new implementation, the system moved from Serttel company to tembici. Now the system seems similar to the https://secure.capitalbikeshare.com/map/ and https://bikesharetoronto.com/system-map/ from PBSC I guess.

**Comment by edumucelli** [comment]
@igormatos, sure, carry on!

**Pull request merged**
