### PR TITLE
GBFS: Remove coast bikeshare

### PR DESCRIPTION
**Pull request by edumucelli**
It is gone from GBFS.

### CODE REVIEW

**Comment by eskerda** [comment]
Two systems seem to protrude from coast bike share:
- http://coastbikeshare.com/stpete/
- http://coastbikeshare.com/tampa/map/

**Comment by edumucelli** [comment]
We should start moving some of the missing SocialBycicles systems on GBFS to its dedicated parser. I will bootstrap something.

**Comment by Altonss** [comment]
It seams like the Coast Bikeshare in Tampa is now operated by hopr, which has a gbfs feed here: https://gbfs.hopr.city/api/gbfs/8/

**Comment by Altonss** [comment]
Well if you look in the details, this feed also contains classical docked bikes (on stations) :)
So personally I would not close this issue. Maybe add the docked bikes for now, before we support floating bikes in #469

**Comment by eskerda** [comment]
It does, but they do not have latitude or longitude. Anyway, I modified the feed https://github.com/eskerda/pybikes/commit/42bb9ac5aa63d7d246ac1e4dde20b2eb131ee9c6 just so we can keep track of it without having this old issue opened

**Comment by Altonss** [comment]
> It does, but they do not have latitude or longitude.

The are available here: https://gbfs.hopr.city/api/gbfs/8/station_information

**Comment by eskerda** [comment]
Then that's a bug on their systems and also on our gbfs implementation. That happens when one of the two entries do not have a field and get overwritten on the dictionary update. Look at gbfs.py on this line https://github.com/eskerda/pybikes/blob/27dc6ea1ef23121238366468698dba07dd1ba927/pybikes/gbfs.py#L92

Maybe you want to take a look

**Pull request closed without merging**
